In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os

In [3]:
os.getcwd()

'C:\\Users\\shubh'

In [4]:
os.chdir("C:\\Users\\shubh\\downloads")

In [7]:
df = pd.read_csv("retail_store_sales.csv")

In [8]:
df.head()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False

In [9]:
df.tail()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,2023-09-03,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,2022-08-12,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,2024-08-24,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,2023-12-30,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,2022-08-06,NaN

In [11]:
df.shape

(12575, 11)

In [12]:
df.size

138325

In [14]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  object
 1   Customer ID       12575 non-null  object
 2   Category          12575 non-null  object
 3   Item              11362 non-null  object
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  object
 8   Location          12575 non-null  object
 9   Transaction Date  12575 non-null  object
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(8)
memory usage: 1.1+ MB

In [16]:
df.describe(include="all")

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
count,12575,12575,12575,11362,11966.000000,11971.000000,11971.000000,12575,12575,12575,8376
unique,12575,25,8,200,NaN,NaN,NaN,3,2,1114,2
top,TXN_2407494,CUST_05,Electric household essentials,Item_2_BEV,NaN,NaN,NaN,Cash,Online,2022-05-30,True
freq,1,544,1591,126,NaN,NaN,NaN,4310,6354,26,4219
mean,NaN,NaN,NaN,NaN,23.365912,5.536380,129.652577,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,10.743519,2.857883,94.750697,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,5.000000,1.000000,5.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,14.000000,3.000000,51.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,23.000000,6.000000,108.500000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,33.500000,8.000000,192.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,41.000000,10.000000,410.000000,NaN,NaN,NaN,NaN

In [17]:
df.isnull().sum()

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [18]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

Discount Applied    33.391650
Item                 9.646123
Price Per Unit       4.842942
Total Spent          4.803181
Quantity             4.803181
Transaction ID       0.000000
Customer ID          0.000000
Category             0.000000
Payment Method       0.000000
Location             0.000000
Transaction Date     0.000000
dtype: float64

In [19]:
df.duplicated().sum()

np.int64(0)

In [22]:
df = df.drop_duplicates()

In [23]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

print(df.columns.tolist())

['transaction_id', 'customer_id', 'category', 'item', 'price_per_unit', 'quantity', 'total_spent', 'payment_method', 'location', 'transaction_date', 'discount_applied']

In [24]:
display(df.head(10))

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False

In [25]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
transaction_id,12575,12575,TXN_2407494,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,12575,25,CUST_05,544,NaN,NaN,NaN,NaN,NaN,NaN,NaN
category,12575,8,Electric household essentials,1591,NaN,NaN,NaN,NaN,NaN,NaN,NaN
item,11362,200,Item_2_BEV,126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_per_unit,11966.0,NaN,NaN,NaN,23.365912,10.743519,5.0,14.0,23.0,33.5,41.0
quantity,11971.0,NaN,NaN,NaN,5.53638,2.857883,1.0,3.0,6.0,8.0,10.0
total_spent,11971.0,NaN,NaN,NaN,129.652577,94.750697,5.0,51.0,108.5,192.0,410.0
payment_method,12575,3,Cash,4310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,12575,2,Online,6354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_date,12575,1114,2022-05-30,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discount_applied,8376,2,True,4219,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    errors="coerce"
)

In [27]:
print(
    "Invalid dates:",
    df["transaction_date"].isna().sum()
)

Invalid dates: 0

In [28]:
numeric_columns = [
    "price_per_unit",
    "quantity",
    "total_spent"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

display(df[numeric_columns].describe())

       price_per_unit      quantity   total_spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [29]:
print("Quantity <= 0:",
      (df["quantity"] <= 0).sum())

print("Price <= 0:",
      (df["price_per_unit"] <= 0).sum())

print("Total Spent < 0:",
      (df["total_spent"] < 0).sum())

Quantity <= 0: 0
Price <= 0: 0
Total Spent < 0: 0

In [30]:
df["calculated_total"] = (
    df["price_per_unit"] * df["quantity"]
)

df["difference"] = (
    df["total_spent"] - df["calculated_total"]
)

display(
    df[
        ["price_per_unit",
         "quantity",
         "total_spent",
         "calculated_total",
         "difference"]
    ].head(10)
)

   price_per_unit  quantity  total_spent  calculated_total  difference
0            18.5      10.0        185.0             185.0         0.0
1            29.0       9.0        261.0             261.0         0.0
2            21.5       2.0         43.0              43.0         0.0
3            27.5       9.0        247.5             247.5         0.0
4            12.5       7.0         87.5              87.5         0.0
5             NaN      10.0        200.0               NaN         NaN
6             5.0       8.0         40.0              40.0         0.0
7            33.5       NaN          NaN               NaN         NaN
8            27.5       1.0         27.5              27.5         0.0
9            36.5       3.0        109.5             109.5         0.0

In [31]:
df["year"] = df["transaction_date"].dt.year

df["month_number"] = (
    df["transaction_date"].dt.month
)

df["month"] = (
    df["transaction_date"].dt.month_name()
)

df["quarter"] = (
    "Q" +
    df["transaction_date"]
    .dt.quarter
    .astype(str)
)

df["year_month"] = (
    df["transaction_date"]
    .dt.to_period("M")
    .astype(str)
)

df["day_of_week"] = (
    df["transaction_date"]
    .dt.day_name()
)

In [32]:
print("Final Dataset Shape:", df.shape)

print("\nMissing Values:")
display(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

display(df.head())

Final Dataset Shape: (12575, 19)

Missing Values:

transaction_id         0
customer_id            0
category               0
item                1213
price_per_unit       609
quantity             604
total_spent          604
payment_method         0
location               0
transaction_date       0
discount_applied    4199
calculated_total    1213
difference          1213
year                   0
month_number           0
month                  0
quarter                0
year_month             0
day_of_week            0
dtype: int64

Duplicate Rows:
0

,transaction_id,customer_id,category,item,price_per_unit,quantity,total_spent,payment_method,location,transaction_date,discount_applied,calculated_total,difference,year,month_number,month,quarter,year_month,day_of_week
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True,185.0,0.0,2024,4,April,Q2,2024-04,Monday
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True,261.0,0.0,2023,7,July,Q3,2023-07,Sunday
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False,43.0,0.0,2022,10,October,Q4,2022-10,Wednesday
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN,247.5,0.0,2022,5,May,Q2,2022-05,Saturday
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False,87.5,0.0,2022,10,October,Q4,2022-10,Sunday

In [33]:
df.to_csv(
    "retail_store_sales_cleaned.csv",
    index=False
)